#modelo arquivo .yml de conexão com o banco.

spring:
  aplication:
    name: introducao_Spring
  database:
    url: jdbc:h2:mem:introSpring
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: "/h2-console"